[[constraint]]
  name = "github.com/drone/drone-go"
  revision = "eaa41f7836a191224ec5702d2458db07882ec269"

[[constraint]]
  name = "gopkg.in/matryer/try.v1"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
